[package]
name = "anathema-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
#anathema = { git = "https://github.com/togglebyte/anathema", branch = "dev" }
anathema = { path = "../anathema" }
